model:
  type: diffusion # dsm and diffusion
  network: dualenc_ver3_base_global
  hidden_dim: 128
  num_convs: 6
  num_convs_local: 4
  cutoff: 6.0
  mlp_act: ReLU
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  num_diffusion_timesteps: 5000
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: false
  TS: True
  feat_dim: 25
  edge_cat_act: swish
  dropout: 0.1

train:
  seed: 2022
  batch_size: 200
  val_freq: 1000
  max_iters: 300000
  max_grad_norm: 3000.0
  anneal_power: 2.0
  optimizer:
    type: adam
    lr: 1.e-3
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 10
    min_lr: 0.00002

dataset:
  train: data/TS/b97d3/train_data.pkl
  val: data/TS/b97d3/val_data.pkl
  test: data/TS/b97d3/test_data.pkl
